development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:7c10cbc0f6a84684169ae5b2b782f0e6@pike.redistogo.com:11364/
  host: pike.redistogo.com
  port: 11364
  password: 7c10cbc0f6a84684169ae5b2b782f0e6
  inline: true
  timeout: 1
  # channel_prefix: chatroom_api_production
  
